import Foundation
import os

private struct ReplacementRuleApplication {
  struct Match {
    let range: NSRange
    let replacement: String
  }

  let matches: [Match]
  let result: String

  init?(rule: ReplacementRule, to text: String) {
    guard let regex = buildRegex(for: rule) else { return nil }
    let template = buildTemplate(for: rule)
    let range = NSRange(text.startIndex..., in: text)
    let matches = regex.matches(in: text, range: range)

    self.matches = matches.map { match in
      Match(
        range: match.range,
        replacement: regex.replacementString(
          for: match,
          in: text,
          offset: 0,
          template: template
        )
      )
    }
    result = regex.stringByReplacingMatches(in: text, range: range, withTemplate: template)
  }
}

public func applyReplacementRules(_ rules: [ReplacementRule], to text: String) -> String {
  rules.reduce(text) { result, rule in
    ReplacementRuleApplication(rule: rule, to: result)?.result ?? result
  }
}

/// Find replacement matches without modifying text. Returns matches with ranges
/// in the original text coordinate system, suitable for overlay positioning.
///
/// Rules are applied sequentially on an intermediate text (same as `applyReplacementRules`),
/// but returned ranges are mapped back to original coordinates using per-position offset
/// tracking. Each prior rule's individual match deltas are tracked so that subsequent rules
/// get position-accurate mappings. When a later rule matches text that was generated by
/// an earlier replacement (not present in original), the mapped range may be approximate
/// and is filtered out by the caller's bounds check.
public func findReplacementMatches(_ rules: [ReplacementRule], in text: String)
  -> [ReplacementMatch]
{
  guard !text.isEmpty else { return [] }

  var matches: [ReplacementMatch] = []
  // Sorted list of (intermediatePosition, cumulativeOffset).
  // For a position p in intermediate text, find the last entry with pos <= p
  // to get the offset. originalPosition = p - offset.
  var offsetEntries: [(pos: Int, offset: Int)] = [(0, 0)]
  var intermediateText = text

  for rule in rules {
    guard let application = ReplacementRuleApplication(rule: rule, to: intermediateText) else {
      continue
    }

    // Record matches and compute offset entries. Offset entries are collected
    // separately and merged after the loop to avoid affecting lookupOffset for
    // matches within the same rule (all matches in a rule use the pre-rule offsets).
    var newEntries: [(pos: Int, offset: Int)] = []
    var shiftSoFar = 0
    for match in application.matches {
      let offset = lookupOffset(at: match.range.location, in: offsetEntries)
      let originalLocation = match.range.location - offset
      matches.append(
        ReplacementMatch(
          range: NSRange(location: originalLocation, length: match.range.length),
          replacement: match.replacement
        ))

      // Track how this replacement shifts subsequent positions.
      let delta = match.replacement.utf16.count - match.range.length
      shiftSoFar += delta
      let oldEnd = match.range.location + match.range.length
      let newEnd = oldEnd + shiftSoFar
      let baseOffset = lookupOffset(at: oldEnd, in: offsetEntries)
      newEntries.append((newEnd, baseOffset + shiftSoFar))
    }
    offsetEntries.append(contentsOf: newEntries)
    offsetEntries.sort { $0.pos < $1.pos }

    intermediateText = application.result
  }

  return matches
}

/// Build an NSRegularExpression for the given rule. Returns nil for invalid or empty patterns.
private func buildRegex(for rule: ReplacementRule) -> NSRegularExpression? {
  let logger = Logger(subsystem: Logger.koechoSubsystem, category: "ReplacementRule")

  let regexPattern: String
  if rule.usesRegularExpression {
    guard !rule.pattern.isEmpty else { return nil }
    regexPattern = rule.pattern
  } else {
    // Filter non-empty, sort longest first to prevent shorter patterns from
    // consuming parts of longer ones (regex alternation is left-to-right).
    let nonEmpty = rule.patternTexts.filter { !$0.isEmpty }.sorted { $0.count > $1.count }
    guard !nonEmpty.isEmpty else { return nil }
    let alternatives = nonEmpty.map { pattern in
      let escaped = NSRegularExpression.escapedPattern(for: pattern)
      return rule.matchesWholeWord ? "\\b\(escaped)\\b" : escaped
    }
    regexPattern = alternatives.joined(separator: "|")
  }

  do {
    return try NSRegularExpression(pattern: regexPattern)
  } catch {
    logger.warning("Invalid regex pattern '\(regexPattern)': \(error.localizedDescription)")
    return nil
  }
}

private func buildTemplate(for rule: ReplacementRule) -> String {
  rule.usesRegularExpression
    ? rule.replacement
    : NSRegularExpression.escapedTemplate(for: rule.replacement)
}

private func lookupOffset(at position: Int, in entries: [(pos: Int, offset: Int)]) -> Int {
  var result = 0
  for entry in entries {
    if entry.pos > position { break }
    result = entry.offset
  }
  return result
}
