import Foundation
import os

struct ReplacementRule: Codable, Identifiable, Equatable, Sendable {
    var id: UUID
    var pattern: String
    var replacement: String
    var usesRegularExpression: Bool
    var matchesWholeWord: Bool

    init(
        id: UUID = UUID(),
        pattern: String,
        replacement: String = "",
        usesRegularExpression: Bool = false,
        matchesWholeWord: Bool = false
    ) {
        self.id = id
        self.pattern = pattern
        self.replacement = replacement
        self.usesRegularExpression = usesRegularExpression
        self.matchesWholeWord = matchesWholeWord
    }

    var displayName: String {
        if pattern.isEmpty { return "New Rule" }
        if replacement.isEmpty { return pattern }
        return "\(pattern) → \(replacement)"
    }
}

struct ReplacementMatch: Equatable {
    let range: NSRange       // Match range in the original text
    let replacement: String  // Replacement string for this match
}

/// Build an NSRegularExpression for the given rule. Returns nil for invalid patterns.
private func buildRegex(for rule: ReplacementRule) -> NSRegularExpression? {
    let logger = Logger(subsystem: "com.ryotapoi.koecho", category: "ReplacementRule")

    let regexPattern: String
    if rule.usesRegularExpression {
        regexPattern = rule.pattern
    } else {
        let escaped = NSRegularExpression.escapedPattern(for: rule.pattern)
        regexPattern = rule.matchesWholeWord ? "\\b\(escaped)\\b" : escaped
    }

    do {
        return try NSRegularExpression(pattern: regexPattern)
    } catch {
        logger.warning("Invalid regex pattern '\(rule.pattern)': \(error.localizedDescription)")
        return nil
    }
}

/// Return the replacement template for the given rule.
private func buildTemplate(for rule: ReplacementRule) -> String {
    rule.usesRegularExpression
        ? rule.replacement
        : NSRegularExpression.escapedTemplate(for: rule.replacement)
}

func applyReplacementRules(_ rules: [ReplacementRule], to text: String) -> String {
    var result = text
    for rule in rules {
        guard !rule.pattern.isEmpty,
              let regex = buildRegex(for: rule) else { continue }
        let template = buildTemplate(for: rule)
        let range = NSRange(result.startIndex..., in: result)
        result = regex.stringByReplacingMatches(in: result, range: range, withTemplate: template)
    }
    return result
}

/// Find replacement matches without modifying text. Returns matches with ranges
/// in the original text coordinate system, suitable for overlay positioning.
///
/// Rules are applied sequentially on an intermediate text (same as `applyReplacementRules`),
/// but returned ranges are mapped back to original coordinates using per-position offset
/// tracking. Each prior rule's individual match deltas are tracked so that subsequent rules
/// get position-accurate mappings. When a later rule matches text that was generated by
/// an earlier replacement (not present in original), the mapped range may be approximate
/// and is filtered out by the caller's bounds check.
func findReplacementMatches(_ rules: [ReplacementRule], in text: String) -> [ReplacementMatch] {
    guard !text.isEmpty else { return [] }

    var matches: [ReplacementMatch] = []
    // Sorted list of (intermediatePosition, cumulativeOffset).
    // For a position p in intermediate text, find the last entry with pos <= p
    // to get the offset. originalPosition = p - offset.
    var offsetEntries: [(pos: Int, offset: Int)] = [(0, 0)]
    var intermediateText = text

    for rule in rules {
        guard !rule.pattern.isEmpty,
              let regex = buildRegex(for: rule) else { continue }
        let template = buildTemplate(for: rule)

        let nsString = intermediateText as NSString
        let fullRange = NSRange(location: 0, length: nsString.length)
        let ruleMatches = regex.matches(in: intermediateText, range: fullRange)

        // Record matches and compute offset entries. Offset entries are collected
        // separately and merged after the loop to avoid affecting lookupOffset for
        // matches within the same rule (all matches in a rule use the pre-rule offsets).
        var newEntries: [(pos: Int, offset: Int)] = []
        var shiftSoFar = 0
        for result in ruleMatches {
            let matchRange = result.range
            let replacement = regex.replacementString(
                for: result,
                in: intermediateText,
                offset: 0,
                template: template
            )

            // Map intermediate position back to original coordinates
            let offset = lookupOffset(at: matchRange.location, in: offsetEntries)
            let originalLocation = matchRange.location - offset
            matches.append(ReplacementMatch(
                range: NSRange(location: originalLocation, length: matchRange.length),
                replacement: replacement
            ))

            // Track how this replacement shifts subsequent positions
            let delta = replacement.utf16.count - matchRange.length
            shiftSoFar += delta
            let oldEnd = matchRange.location + matchRange.length
            let newEnd = oldEnd + shiftSoFar
            let baseOffset = lookupOffset(at: oldEnd, in: offsetEntries)
            newEntries.append((newEnd, baseOffset + shiftSoFar))
        }
        offsetEntries.append(contentsOf: newEntries)
        offsetEntries.sort { $0.pos < $1.pos }

        intermediateText = regex.stringByReplacingMatches(
            in: intermediateText,
            range: fullRange,
            withTemplate: template
        )
    }

    return matches
}

private func lookupOffset(at position: Int, in entries: [(pos: Int, offset: Int)]) -> Int {
    var result = 0
    for entry in entries {
        if entry.pos > position { break }
        result = entry.offset
    }
    return result
}
